<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="adabot">


    <!-- Create the chassis geometry (for visuals and collisions) -->
    <xacro:property name="chassis_geometry">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${ch_length} ${ch_width} ${ch_height}" />
        </geometry>
    </xacro:property>




    <!-- Create the wheel geometry (for visuals and collisions) -->
    <xacro:property name="wheel_geometry">
        <!-- Cylinders default with their height along the z axis -->
        <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
        <geometry>
            <!-- <cylinder length="${wh_length}" radius="${wh_radius}" /> -->
            <sphere radius="${wh_radius}" />
        </geometry>
    </xacro:property>




    <!--
         Macro for creating wheels
            reflect_lr : is the wheel left (-1) or right (1)
            reflect_fr : is the wheel front (1) or rear (-1)
            suffix     : give the wheel a unique name
    -->
    <xacro:macro name="wheel" params="reflect_lr reflect_fr suffix">

        <!-- The name of the current wheel -->
        <xacro:property name="wheel_name" value="${suffix}_wheel" />

        <!-- Add the wheel's Gazebo material -->
        <xacro:gz_wheel_material name="${wheel_name}" />

        <!-- The wheel's rigid body -->
        <link name="${wheel_name}">
            <visual>
                <xacro:insert_block name="wheel_geometry" />
                <material name="black" />
            </visual>
            <collision>
                <xacro:insert_block name="wheel_geometry" />
            </collision>
            <inertial>
                <mass value="${wh_mass}" />
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <inertia
                    ixx="${(1/12)*wh_mass*(3*wh_radius**2 + wh_length**2)}"
                    ixy="0"
                    ixz="0"
                    iyy="${(1/12)*wh_mass*(3*wh_radius**2 + wh_length**2)}"
                    iyz="0"
                    izz="${(1/2)*wh_mass*wh_radius**2}"
                    />
            </inertial>
        </link>

        <!-- Connect the wheel to the chassis -->
        <joint name="${wheel_name}_joint" type="continuous">
            <parent link="chassis" />
            <child link="${wheel_name}" />
            <origin xyz="${ch_length/2*reflect_fr} ${(wh_length+ch_width)/2*reflect_lr} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <limit effort="10" velocity="10" />
        </joint>

        <!--
             Attach a VELOCITY controller to the wheel's joint
                Any changes to the wheel joint's name will need to be reflected
                  in 'adabot.control.yaml' and 'adabot.control.launch'.
        -->
        <transmission name="${wheel_name}_transmission" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${wheel_name}_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${wheel_name}_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <!-- Add wegs to this wheel -->
        <xacro:weg wheel="${suffix}" number="1" parent="${wheel_name}" total="5" />
        <xacro:weg wheel="${suffix}" number="2" parent="${wheel_name}" total="5" />
        <xacro:weg wheel="${suffix}" number="3" parent="${wheel_name}" total="5" />
        <xacro:weg wheel="${suffix}" number="4" parent="${wheel_name}" total="5" />
        <xacro:weg wheel="${suffix}" number="5" parent="${wheel_name}" total="5" />

    </xacro:macro>




    <!-- Create the weg geometry (for visuals and collisions) -->
    <xacro:property name="weg_geometry">
        <origin xyz="${wh_radius/2} 0 0" rpy="0 0 0" />
        <!-- <origin xyz="${wh_radius} 0 0" rpy="0 0 0" /> -->
        <geometry>
            <box size="${wg_length} ${wg_width} ${wg_height}" />
        </geometry>
    </xacro:property>




    <!-- Create a geometry for the weg tip -->
    <xacro:property name="weg_tip_geometry">
        <!-- <origin xyz="${wh_radius} 0 0" rpy="0 0 0" /> -->
        <geometry>
            <sphere radius="${wt_radius}" />
        </geometry>
    </xacro:property>


    <!--
         Macro for creating wegs
            wheel  : the suffix of the parent wheel
            number : a unique identifier for each weg
            parent : the full name of the parent link
            total  : the number of wegs (used to calculate angles)
    -->
    <xacro:macro name="weg" params="wheel number parent total">

        <!-- The name of the current weg (based on the parent wheel's name) -->
        <xacro:property name="weg_name" value="${wheel}_weg_${number}" />

        <!-- The weg's rigid body -->
        <link name="${weg_name}">
            <visual>
                <xacro:insert_block name="weg_geometry" />
                <material name="white" />
            </visual>
            <collision>
                <xacro:insert_block name="weg_geometry" />
            </collision>
            <inertial>
                <mass value="${wg_mass}" />
                <inertia
                    ixx="${(1/12)*wg_mass*(wg_width**2 + wg_height**2)}"
                    ixy="0"
                    ixz="0"
                    iyy="${(1/12)*wg_mass*(wg_length**2 + wg_height**2)}"
                    iyz="0"
                    izz="${(1/12)*wg_mass*(wg_length**2 + wg_width**2)}"
                    />
            </inertial>
        </link>

        <!-- Connect the weg to the wheel with a prismatic joint -->
        <joint name="${weg_name}_joint" type="prismatic">
        <!-- <joint name="${weg_name}_joint" type="fixed"> -->
            <parent link="${parent}" />
            <child link="${weg_name}" />
            <origin xyz="0 0 0" rpy="0 ${2 * PI * (number/total)} 0" />
            <limit upper="${wh_radius * 0.7}" lower="0" effort="10" velocity="10" />
        </joint>

        <!--
             Attach a POSITION controller to each weg prismatic joint
                Any changes to the wheel joint's name will need to be reflected
                  in 'adabot.control.yaml' and 'adabot.control.launch'.
                Also note that, technically, all wegs for a single joint should be
                  controlled together (a single transimission for each weg set).
                  However, I do not think this will be possible given that the transmission
                  interface requires a single process value for each motor.
        -->
        <transmission name="${weg_name}_transmission" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${weg_name}_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${weg_name}_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>


        <!-- Attach a sphere to the end of the weg for better physics (less jitter) -->
        <link name="${weg_name}_tip">
            <visual>
                <xacro:insert_block name="weg_tip_geometry" />
                <material name="black" />
            </visual>
            <collision>
                <xacro:insert_block name="weg_tip_geometry" />
            </collision>
            <inertial>
                <mass value="${wt_mass}" />
                <inertia
                    ixx="${(2/5) * wt_mass * wt_radius * wt_radius}"
                    ixy="0"
                    ixz="0"
                    iyy="${(2/5) * wt_mass * wt_radius * wt_radius}"
                    iyz="0"
                    izz="${(2/5) * wt_mass * wt_radius * wt_radius}"
                    />
            </inertial>
        </link>

        <!-- Connect the weg tip to the weg -->
        <joint name="${weg_name}_tip_joint" type="fixed">
            <parent link="${weg_name}" />
            <child link="${weg_name}_tip" />
            <!-- The 0.95 is a fudge factor so that weg tips are not aligned with the
                 wheel radius when commanded to zero. -->
            <origin xyz="${wh_radius * 0.95 - wt_radius} 0 0" rpy="0 0 0" />
        </joint>

    </xacro:macro>

</robot>
